### ISSUE TITLE
Click edge (sequence flow) error (reported at #265)

### ISSUE THREAD

**Issue by lucianodltec** [bpmn-io/diagram-js#531] opened 2021-01-25 12:38 UTC
__Describe the Bug__

After adding some coments, change its text and click on it, the digram stops working.

__Steps to Reproduce__

1. use https://github.com/lucianodltec/vue-bpmn-modeler example app (npm run serve)
2. add some element on digram
3. add some coments with text
4. click on the coments and watch for console errors

![105646713-2f75b480-5e80-11eb-8cda-5d03f29e717e](https://user-images.githubusercontent.com/10486864/105706962-fb86a780-5ef0-11eb-8280-328282382cb6.png)

__Expected Behavior__

Not raise non handled exceptions. There is already a solution provided for "opsolve" check https://github.com/opsolve/diagram-js/commit/9d94266b1928ddb491824a049eae6fdd9f18ef5c

I think its just a matter of merging this code.

__Environment__

Please complete the following information:

 - Browser: Chrome 88

 - OS: Windows 10
 - Library version: 7.0.0

**Comment by nikku** [comment] 2021-01-25 13:18
Could you provide me with a screen capture that shows what exact sequence of events leads to this bug?

**Comment by lucianodltec** [comment] 2021-01-25 14:30
Actually, it´s pretty simple to reproduce.

I notice, it always happens when i try to add a comment to the sequence flow.

https://user-images.githubusercontent.com/10486864/105719025-9cc92a00-5f00-11eb-825e-9d265e95cbf6.mp4

**Comment by nikku** [comment] 2021-01-25 14:47
This is due to the fact that auto-place / append does not work on sequence flows. What would be your expected behavior, if you _append_ a comment to a sequence flow? Where should it be appended to?

**Comment by lucianodltec** [comment] 2021-01-25 14:51
Yes, ideed I tried bmpn.io to check for this and saw it´s does not provide comments for sequence flow.

Sound like a feature request then. 

The expect behaviour would be the comment appended do the sequence flow center's.

Is is possible?

Thanks in advance and for the quick replies.

**Comment by nikku** [comment] 2021-01-25 15:04
You may hook into the `autoPlace` event to return a proper position for your comment, if automatically placed onto a sequence flow: https://github.com/bpmn-io/diagram-js/blob/develop/lib/features/auto-place/AutoPlace.js#L43.

**Comment by nikku** [comment] 2021-01-25 15:05
Closing this issue as it is not a bug, but caused by a miss-use of our existing APIs.

**Closed by nikku** 2021-01-25 15:04 UTC
Labels: bug, help wanted
