### ISSUE TITLE
Documentation For Diagram JS

### ISSUE THREAD

**Issue by Priya-Ahuja** [bpmn-io/diagram-js#303] opened 2018-11-21 10:45 UTC
__Is your feature request related to a problem? Please describe.__

__Describe the solution you'd like__

__Describe alternatives you've considered__

__Additional context__

**Comment by pinussilvestrus** [comment] 2018-11-22 07:38
Hi @Priya-Ahuja 
So if I understand you correctly you're just looking for a documentation? You can find an overall explanation [here](https://bpmn.io/toolkit/bpmn-js/walkthrough/#bpmn-js-internals).

At the moment there is no standalone documentation for diagram.js. Also see this [issue](https://github.com/bpmn-io/diagram-js/issues/78). Maybe the [example app](https://github.com/bpmn-io/diagram-js/tree/master/example) can help to understand how things are working.

However the previous title of this topic makes me thinking that you had a problem. Maybe you can give us more details in the form @nikku mentioned it. If you've opened this issue just for getting to know a general documentation, we will close it since there is no real issue or feature request.

**Comment by nikku** [comment] 2018-11-22 08:39
> I have to know about how all the modules (specially in lib) are working.

Consider looking into our comprehensive [test suite](https://github.com/bpmn-io/diagram-js/tree/master/test) if you'd like to understand the detailed functioning of the library. For a high level overview how diagram-js helps you build editors I recommend reading through the [bpmn-js architecture walkthrough](https://bpmn.io/toolkit/bpmn-js/walkthrough/), too.

**Comment by nikku** [comment] 2018-11-22 08:39
Closed as a duplicate of https://github.com/bpmn-io/diagram-js/issues/78.

**Closed by nikku** 2018-11-22 08:39 UTC
Labels: help wanted
