### ISSUE TITLE
Be Able to Avoid Endless Loop When Listening for and Firing Same Event

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/diagram-js#525] opened 2021-01-21 10:34 UTC
Listening for an event and firing that same event in the callback will result in an endless loop:

```javascript
const listener = () => {
  eventBus.fire('foo');
};

eventBus.on('foo', listener);

eventBus.fire('foo');
```

Currently, the only way to prevent this is to stop and start listening again in the callback:

```javascript
const listener = () => {
  eventBus.off('foo', listener);

  eventBus.fire('foo');

  eventBus.on('foo', listener);
};

eventBus.on('foo', listener);

eventBus.fire('foo');
```

There should be a more elegant way of avoiding this kind of situation. Sometimes the user [might not be aware that the event he is listening for is fired through the callback](https://github.com/bpmn-io/align-to-origin/issues/2).

Related https://github.com/bpmn-io/diagram-js/issues/524

**Comment by nikku** [comment] 2021-01-21 13:54
I'm not sure if this is something we should solve / support in an elegant way on the `EventBus` layer.

Solely from the API perspective, this looks like expected behavior to me: If I fire `foo` inside a listener, listening for `foo`, surely that is going to result in an endless loop? What else should I expect?

**Comment by philippfromme** [comment] 2021-01-21 14:03
I'm not saying we should solve this in the event bus. This issue is simply meant to start the discussion. 😉

**Comment by nikku** [comment] 2021-01-21 15:23
What is the concrete instance of that problem? I guess, looking into https://github.com/bpmn-io/align-to-origin/issues/2 it is the fact that you cannot safe the diagram on `commandStack.changed` when some component changes the command stack on diagram save?

**Comment by philippfromme** [comment] 2021-01-21 15:32
Yes, this is the original issue. There is no way of listening to _the diagram has changed_ to export it when using the align-to-origin module.

**Comment by nikku** [comment] 2021-01-27 13:49
Let's close this one. Now that https://github.com/bpmn-io/diagram-js/issues/524 is closed a simple way to achieve this is:

```
function listenAndRepeat() {
  
  eventBus.fire('listenOnlyOnce', ...);

  eventBus.once('listenOnlyOnce', listenAndRepeat);
}

eventBus.once('listenOnlyOnce', listenAndRepeat);
```

In the above case `listenAndRepeat` can safely fire `listenAndRepeat` without looping.

**Closed by nikku** 2021-01-27 13:49 UTC
Labels: enhancement, help wanted
