### ISSUE TITLE
Ctrl + C crashes when root element is clicked and canvas.getRootElement was called

### ISSUE THREAD

**Issue by StrohMax** [bpmn-io/diagram-js#313] opened 2019-03-12 16:36 UTC
__Describe the Bug__

When clicking on the root element (process or collaboration) of a diagram and pressing Ctrl + C, a bunch of errors is thrown. This bug only appears, when we call bpmnJS.get("canvas").getRootElement(). When we outcomment this call everything works fine.
Background of this call is that we want to load different information about the clicked elements. So we need to get the root element in case it was clicked. When selecting an element, we listen to the selection.changed event and call our methods with the selected elements. To be able to correctly work e.g. your copy command this event returns an empty array as newSelection in case the root element was clicked. But we need to get this root element to do our stuff, so we used the bpmnJS.get("canvas").getRootElement() method to get the root element in this case.

I debugged a bit through your code and recognized, that when the getRootElement method is called, the newSelection array of the selection.changed event first is empty (because the clicked element is still undefined), but later on includes the root element which crashes when pressing Ctrl + C afterwards. I wanted to be sure and looked at the array i get from bpmnJS.get("selection").get() after calling getRootElement method and the result was the same:
If we use the getRootElement method, the array returned by selection.get() included the root element, if we outcomment the use of the getRootElement method, the array returned by selection.get() is empty.

Here is the code snippet we use (including my loggings so you better understand whats happening in the gifs):

```typescript
const eventBus = this.bpmnJs.get("eventBus");

eventBus.on("selection.changed", (event: any) => {
    event.stopPropagation();
    event.preventDefault();

    $(":focus").blur();
    console.info(event);
    if (event.newSelection.length) {
        this.loadElementAttributes(event.newSelection[0]);
    } else {
        this.loadElementAttributes();
    }
});

private loadElementAttributes(clickedDomElement?: any) {
    console.info("LOADING ATTRIBUTES OF ELEMENT:");
    console.info("Clicked element (of selection event):");
    // clickedDomElement is always undefined
    console.info(clickedDomElement);
    if (!clickedDomElement) {
        const canvas = this.bpmnJs.get("canvas");
        clickedDomElement = canvas.getRootElement();
        // After this call, the root is set to the newSelection array of the
        // selection.changed event and selection.get() returns the root element
        // If outcommented, both arrays stay empty
        console.info("After calling canvas.getRootElement!");
    }
    // [...]
    const selectedElements = bpmnJs.get("selection").get();
    console.info("Elements returned by bpmnJs.get(\"selection\").get() method:");
    console.info(selectedElements);
    // [...]
}
```

GIF: getRootElement called, error appeares
![copy-root-getrootelement-method-called](https://user-images.githubusercontent.com/29775599/54218157-51185d80-44ed-11e9-98bd-54dd7096e864.gif)

GIF: getRootElement outcommented, everything works
![copy-root-working](https://user-images.githubusercontent.com/29775599/54218159-51b0f400-44ed-11e9-8de8-f5621d45f93a.gif)

__Steps to Reproduce__

1. Take a code snippet where bpmnJS.get("canvas").getRootElement() method is called when selecting an element
2. Open a random diagram
3. Open Dev-Console of the browser
4. Click on the root element
5. Press Ctrl + C
6. Look at the console output

__Expected Behavior__

I don't know exactly what the correct behavior is here. But I guess it should be one of these two:

1. The call of the getRootElement method does not select the root element (as it is never selected in other cases e.g. when clicked)

or (maybe nr 1 is needed for some other logic, i dont know)

2. When copying elements (pressing Ctrl + C), the system shouldn't do anything in case the given element is a process/collaboration element

__Environment__

Please complete the following information:

 - Browser: Firefox 65.0.2, Chrome 72.0.3626.121
 - OS: Windows 7
 - Library version: bpmn-js v3.2.1, diagram-js v3.1.3

**Comment by StrohMax** [comment] 2019-03-12 16:55
Unfortunately, I could not find out where the bug comes from. I looked into the getRootElement and don't know what should trigger the modeler to select the root element... I hope you guys have an idea what's going wrong here...

**Comment by StrohMax** [comment] 2019-03-13 12:27
Oh sorry, yeah of course:
![grafik](https://user-images.githubusercontent.com/29775599/54278807-bde63300-4593-11e9-97bb-12ca5006d13c.png)

**Comment by philippfromme** [comment] 2019-03-25 09:51
I've used the code you provided. Wasn't able to reproduce the issue. Are you sure there's no other code messing around with the selection?

**Comment by nikku** [comment] 2019-04-09 15:58
Closing this issue due to missing feedback. We're happy to re-open it if we receive additional feedback on the matter.

**Closed by nikku** 2019-04-09 15:58 UTC
Labels: help wanted

**Comment by StrohMax** [comment] 2019-04-16 11:11
Sorry for the late respond.

We are using Selection only in one other part of the code, which is not called in this scenario. I also outcommented this part to be sure and had the same errors. Other occurancies / uses of the bpmnJS selection is that we ask to get the selected element as I described above. This is triggered by a few eventhandlers. But nothing else. Do you have any idea what could be wrong? Is it called to early or does it maybe collide with something else I could check?

**Comment by StrohMax** [comment] 2019-04-16 11:13
To be clear: I outcommented every other occurance of the use of bpmnJs selection than the one described (const selectedElements = bpmnJs.get("selection").get();)
