### ISSUE TITLE
Context pad announces `trigger` with every mouse movement on hover

### ISSUE THREAD

**Issue by smbea** [bpmn-io/diagram-js#828] opened 2023-11-14 15:14 UTC
### Describe the Bug

Context pad announces `trigger` with every mouse movement on hover. This seems to have appeared when append preview stuff was added: https://github.com/bpmn-io/diagram-js/pull/807/files#diff-6d674faf358204aeb4b308e49584a5b425dd2b59dcef70ebfb108f894b96db5dR233

https://github.com/bpmn-io/diagram-js/assets/25825387/54fd4d6d-8906-4aa7-8a4d-264756742f15

### Steps to Reproduce

1. Log `contextPad.trigger` events
2. Open context pad and move through entries

### Expected Behavior

Fire event only when entry is actually triggered.

### Environment

Please complete the following information:

 - Browser: [e.g. IE 11, Chrome 69]
 - OS: [e.g. Windows 7]
 - Library version: [e.g. 2.0.0]

**Comment by smbea** [comment] 2023-11-14 15:14
fyi @philippfromme

**Comment by philippfromme** [comment] 2023-11-14 15:15
Oh oh. I'll look into this.

**Comment by philippfromme** [comment] 2023-12-12 16:10
I cannot reproduce this issue. `trigger` is only called when moving the mouse in and out of an entry.

![brave_5759rGFZMG](https://github.com/bpmn-io/diagram-js/assets/7633572/ab6878b5-883c-4c78-87ef-e1368ea8c852)

I will close this issue for now. Feel free to reopen if there is an issue with the hover behavior.

**Closed** 2023-12-12 16:10 UTC
Labels: bug, ready
